---

# Configure system users access to MariaDB

- name: DEB | Configure MariaDB access for Ansible mysql_user module
  file: src=/etc/mysql/debian.cnf
        dest=/root/.my.cnf
        owner=root group=root
        state=link
        force=yes

- name: DEB | Set MariaDB debian-sys-maint password for service control
  mysql_user: name=debian-sys-maint 
              password={{ galera_maintenance_password }} 
              host=localhost 
              state=present

- name: DEB | Configure defaults-file for debian-sys-maint service user
  template: src=debian.cnf.j2 
            dest=/etc/mysql/debian.cnf 
            owner=root 
            group=root 
            mode=0640
